name: .NET Core

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '2.2.103', '3.1.100' ]
    name: Dotnet ${{ matrix.dotnet }}
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Test
      run: dotnet test ./tests/tests.csproj
    - name: Build with dotnet
      run: dotnet build --configuration Release
